/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.1.441 */
/* Module Version: 5.7 */
/* Sat Jul 18 00:45:59 2020 */

/* parameterized module instance */
PLL __ (.CLKI( ), .CLKOP( ), .LOCK( ));
